cloud-barista/mc-data-manager

.env, Dockerfile, docker-compose.yaml, entrypoint.sh, internal/log/log.go
- Dockerfile 생성
- docker compose 파일 생성
- Update : Binary 파일 경로에 log/data-manger.log 생성
=> Add Dockerfile and docker-compose.yml for Docker setup

.github/workflows/continuous-delivery.yaml, .github/workflows/continuous-integration.yaml
- CI 워크플로우 추가 > act 로컬 테스트 완료
- CD 워크플로우 추가
=> Add CI/CD pipeline configuration

websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml, websrc/serve/serve.go
- serve.go 기반으로 다시 스웨거 문서 생성
- 프로젝트 명 변경
=> update swagger, from  serve.go doc

docker-compose.yaml, internal/log/log.go
- docker compose.yaml , log.go  주석 영문화
=> update comment, 영문화

docker-compose.yaml
- Resolve Docker Compose volume bind mode directory owner issue
- Create volume first with init_chown_volumes container
=> update : volume bind mode , Dir chage owner

README.md
- fixed directory path of fuction-specification.md and usage-guide.md in readme.md
=> fix doc dir in readme.md

docker-compose.yaml, websrc/controllers/generateHandlers.go, websrc/controllers/migrationGCPHandlers.go, websrc/controllers/migrationHandlers.go, websrc/controllers/migrationNCPHandlers.go, websrc/controllers/migrationNoSqlHandlers.go, websrc/controllers/migrationS3Handlers.go
- docker compose update
- swagger update & add  file parameter for GCP
=> update : swwagger docs  gcp param update

websrc/controllers/generateHandlers.go, websrc/controllers/migrationGCPHandlers.go, websrc/controllers/migrationHandlers.go, websrc/controllers/migrationNCPHandlers.go, websrc/controllers/migrationNoSqlHandlers.go, websrc/controllers/migrationS3Handlers.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml
- GCP관련 Swagger Accept type 변경
=> update : swagger update Gcp Accept

websrc/controllers/migrationNoSqlHandlers.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml
=> update swagger parametype

config/config.go, internal/auth/base.go, internal/auth/cmdstruct.go, websrc/controllers/gendata.go, websrc/controllers/generateHandlers.go, websrc/controllers/migrationGCPHandlers.go, websrc/controllers/migrationHandlers.go, websrc/controllers/migrationNCPHandlers.go, websrc/controllers/migrationNoSqlHandlers.go, websrc/controllers/migrationS3Handlers.go, websrc/controllers/migrationStructs.go, websrc/controllers/publicfunc.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml
- Added GCPcredentialJson to store GCP credentials in JSON format.
- Added DatabaseId to uniquely identify the database in GCP.
- Updated relevant functions to handle the new parameters.
=>     Add GCPcredentialJson and DatabaseId to GcpParams

websrc/controllers/generateHandlers.go, websrc/controllers/migrationGCPHandlers.go, websrc/controllers/migrationHandlers.go, websrc/controllers/migrationNCPHandlers.go, websrc/controllers/migrationNoSqlHandlers.go, websrc/controllers/migrationS3Handlers.go, websrc/controllers/migrationStructs.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml
- added gcpCredentialJson parameter to migrationForm
=> add gcpCredentialJson to migrationForm

Dockerfile
- Dockerfile: Name Application Setup stage to 'prod'
=> fix : CD workflow 

README.md, docker-compose.yaml, docs/Datamanager-Docker-Guide.md, docs/Datamanager-Function-Specification.md
=> Add docker guide doc

cmd/server.go, docker-compose.yaml, go.mod, go.sum, internal/zerolog/logger.go, main.go
- 로그 파일 디렉토리 수정
- zerolog 추가
- 적용예정
=> Update : docker compose , Add : Zero log

data/var/run/data-manager/task/task.json, models/basicTask.go, models/enums.go, pkg/objectstorage/s3fs/s3fs.go, pkg/utils/utils.go, service/task/task.go, web/css/styles.css, web/js/scripts.js, web/templates/content.html, web/templates/header.html, web/templates/task.html, websrc/controllers/backupHandlers.go, websrc/controllers/generateHandlers.go, websrc/controllers/migrationGCPHandlers.go, websrc/controllers/migrationHandlers.go, websrc/controllers/migrationNCPHandlers.go, websrc/controllers/migrationNoSqlHandlers.go, websrc/controllers/migrationS3Handlers.go, websrc/controllers/pageHandlers.go, websrc/controllers/publicfunc.go, websrc/controllers/restoreHandlers.go, websrc/controllers/taskHandlers.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml, websrc/routes/taskRoutes.go, websrc/serve/serve.go
- Task UI add
- ( HTML 네비게이션 미설정)
- Task 스케줄 TZ 별 go routine 분리
- Task cron( 반복 일정), startTime( 예약 일정), instance ( 요청 인스턴스)
- swagger update
=> Add : task ui

websrc/controllers/migrationHandlers.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml, websrc/serve/serve.go
- fix api route
- fix api route
=> fix: migrate route

web/js/scripts.js
- web-ui 요청 uri 변경
- web-ui 요청 uri 변경
=> Fix: update request uri

web/templates/index.html
from migration to migrate
- nav link from migration to migrate 
- nav link from migration to migrate 
=> Fix: update nav link

docker-compose.yaml
- change volume bind path
- change volume bind path
=> Fix: chmod dir

web/css/styles.css
- update css color theme
- update css color theme
=> Style: update-css

web/js/scripts.js
- Add event listener "message" 
=> Add : web ui listen event 'message'

docs/Datamanager-Docker-Guide.md
=> Fix : DemoGuide

docs/Datamanager-Docker-Guide.md
=> Docs: fix docker guide

websrc/controllers/generateHandlers.go
- fix rdbms , nrdbms generate logic
=> Fix : generate handler

pkg/rdbms/mysql/mysql.go, service/rdbc/rdbc.go, web/templates/mig-mysql.html
- Fix : rdbc mysql logger change
=> Fix : rdbc mysql logger change

README.md, websrc/controllers/healthCheckHandlers.go, websrc/controllers/serivceHandlers.go, websrc/docs/docs.go, websrc/docs/swagger.json, websrc/docs/swagger.yaml
- swagger update
- Update README
- Add API Guide
=> Docs: Update Docs
